version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sopos
    ports:
      - 8889:8890
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: /usr/src/app
    restart: unless-stopped
    ports:
      - 3002:3000
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=sopos
      - DB_PORT=8890
    stdin_open: true
    tty: true
volumes:
  db: