version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: node-soposing
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST = localhost
      - MYSQL_USER = user
      - MYSQL_PASS = password
      - MYSQL_DB = sopos
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:3000"
    container_name: nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD = root
      - MYSQL_USER = user
      - MYSQL_PASSWORD = password 
      - MYSQL_DATABASE = sopos
    container_name: mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysql-app
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: phpmyadmin-app
networks:
  frontend:
  backend: